artifact_uri: file:///mlflow_data/artifacts/0/e34dce0e3ef64c63ae26ab189b94af0d/artifacts
end_time: 1758770685408
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: e34dce0e3ef64c63ae26ab189b94af0d
run_name: RandomForest_Manga_Prediction
run_uuid: e34dce0e3ef64c63ae26ab189b94af0d
source_name: ''
source_type: 4
source_version: ''
start_time: 1758770681972
status: 4
tags: []
user_id: airflow
