artifact_uri: file:///mlflow_data/artifacts/491280676728614918/e07d5ce7d70e48a39ff0e5abf1cdfd15/artifacts
end_time: 1759517454059
entry_point_name: ''
experiment_id: '491280676728614918'
lifecycle_stage: active
run_id: e07d5ce7d70e48a39ff0e5abf1cdfd15
run_name: RandomForest_Manga_Prediction
run_uuid: e07d5ce7d70e48a39ff0e5abf1cdfd15
source_name: ''
source_type: 4
source_version: ''
start_time: 1759517448792
status: 3
tags: []
user_id: airflow
