artifact_uri: file:///mlflow_data/artifacts/0/3f94eaa91d2a4b999c0551253e663915/artifacts
end_time: 1758786335558
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 3f94eaa91d2a4b999c0551253e663915
run_name: Model_Evaluation
run_uuid: 3f94eaa91d2a4b999c0551253e663915
source_name: ''
source_type: 4
source_version: ''
start_time: 1758786335336
status: 3
tags: []
user_id: airflow
