artifact_uri: file:///mlflow_data/artifacts/0/4bc3d12c48f9407ca93d830eaa286855/artifacts
end_time: 1758770671582
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 4bc3d12c48f9407ca93d830eaa286855
run_name: RandomForest_Manga_Prediction
run_uuid: 4bc3d12c48f9407ca93d830eaa286855
source_name: ''
source_type: 4
source_version: ''
start_time: 1758770667956
status: 4
tags: []
user_id: airflow
