artifact_uri: file:///mlflow_data/artifacts/491280676728614918/be1ecef19b514dfba4331a9c270bbee6/artifacts
end_time: 1759510557810
entry_point_name: ''
experiment_id: '491280676728614918'
lifecycle_stage: active
run_id: be1ecef19b514dfba4331a9c270bbee6
run_name: RandomForest_Manga_Prediction
run_uuid: be1ecef19b514dfba4331a9c270bbee6
source_name: ''
source_type: 4
source_version: ''
start_time: 1759510552548
status: 3
tags: []
user_id: airflow
