artifact_uri: file:///mlflow_data/artifacts/0/673c2f0773ea43d9ae63fc11d0a89cc8/artifacts
end_time: 1758786334324
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 673c2f0773ea43d9ae63fc11d0a89cc8
run_name: RandomForest_Manga_Prediction
run_uuid: 673c2f0773ea43d9ae63fc11d0a89cc8
source_name: ''
source_type: 4
source_version: ''
start_time: 1758786330400
status: 3
tags: []
user_id: airflow
